---
- name: Create "sshers" group
  group:
    name: sshers

- name: Add user to "sshers" group
  user:
    name: "{{ item.user }}"
    groups: sshers
    append: true # --> user is not removed from any other group
  loop: "{{ users }}"

- name: Configure SSH server
  template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart SSH service