---
- name: Create .ssh directory for every user
  file:
    path: "/home/{{ item.user }}/.ssh"
    state: directory
    owner: "{{ item.user }}"
    group: users
    mode: 0700
  loop: "{{ users }}"

- name: Copy authorized_keys to home directories
  copy:
    content: "{{ item.authorized_keys }}"
    dest: "/home/{{ item.user }}/.ssh/authorized_keys"
    owner: "{{ item.user }}"
    group: users
    mode: 0600
  loop: "{{ users }}"